export { default as StartScreen } from './StartScreen'
export { default as LoginScreen } from './LoginScreen'
export { default as RegisterScreen } from './RegisterScreen'
export { default as ResetPasswordScreen } from './ResetPasswordScreen'
export { default as Dashboard } from './Dashboard'
export { default as QuizIndex } from './QuizIndex'
export { default as Story } from './Story'
export { default as MCQQuiz} from './MCQQuiz'
export {default as TQQuiz} from './TQQuiz'
export { default as Answer} from './Answer'
export {default as TextAnswer} from './TextAnswer'
export {default as Summary} from './Summary'
export {default as Link} from './Link'
export {default as Medal} from './Medal'
